### PR TITLE
Add FEC desktop header

### PR DESCRIPTION
**Pull request by adborden**
This makes progress on https://github.com/18F/fec-eregs/issues/88 to integrate eregs UI with betaFEC. Adds the desktop header (mobile is not supported yet).

Depends on:
- [x] https://github.com/eregs/regulations-site/pull/367
- [x] https://github.com/18F/fec-style/pull/369
- [x] Adjust header sizes for new FEC header
- [x] bump fec-style once the version is rev'd

You can see a preview of this work https://fec-adborden-eregs.18f.gov/

- Better integrates fec-style by [scaling the `rem`s used for sizing components](https://github.com/18F/fec-style/pull/369).
- Updates colors using the new FEC color palette.
- Fixes TOC margin issues from upstream changes in eregs.
- Locks our `regulations-site` dependency to a specific version to prevent changes taking us by surprise.

screenshot from 2016-05-26 10-17-56

### CODE REVIEW

**Comment by adborden** [comment]
cc @noahmanger @18F/fec-legal

**Comment by adborden** [comment]
This is ready for review, we're just waiting on some dependencies to land before merging. Any feedback would be helpful.

**Comment by adborden** [comment]
This is ready for review.

**Comment by adborden** [comment]
@edmullen can you take a look ? https://fec-adborden-eregs.18f.gov/

**Comment by noahmanger** [comment]
Niiiice. Only questions:
- Is there a reason you chose to go with fixing the header?
- I can't tell why the mega menu isn't working, but I noticed it isn't

**Comment by edmullen** [comment]
As preface to this, I an not totally current on the development of the new internal header besides [fec-style issue 366](https://github.com/18F/openFEC/issues/1663) and [fec-style pr 366](https://github.com/18F/fec-style/pull/366). I see a few display issues that aren't consistent.

**The whole header shouldn't be fixed.**

- As @noahmanger pointed out, the whole header shouldn't be fixed. The subheader that hasn't yet been added is the element that should become affixed in [the way your mockup suggested]
(https://adborden.github.io/eregs-scroll-prototype/). The header elements included here should scroll out of the viewport normally.

- image

**Mega menu thoughts**

I have some concerns about the mega menu in this context, mostly around the level of effort of implementing it here. I'm not sure what that LOE is, but imagine it could be significant. If it is high, I think we should chat about if it is worth it right now to implement. (cc @noahmanger)

**Beta site label should align with FEC lockup.**

- 

**The seal isn't loading on Firefox.**

- image

**Extra space on mobile where nav is on desktop.**

- image

**Mobile nav menu is cut off.**

- image

**Nav font should be serif/Gandhi**
- image

cc @adborden

**Comment by porta-antiporta** [comment]
commenting to get updates.

**Comment by adborden** [comment]
@noahmanger @edmullen on the fixed header: you both are correct. The header is fixed out of the box in eregs, so adding the scroll behavior is it's own chunk of work. I wanted to tackle that in another PR and  get feedback on the current state first, especially because the new header design is a little slimmer than before and wasn't sure if the plan for scroll behavior would change.

Re: the megamenu and mobile nav menu, I had to add an `overflow: hidden` on the header container to prevent some wrapping issues with the smaller breakpoints and that is why the menus are cutoff or don't appear. I think I will disable the menus for this PR, since the mobile cutoff looks pretty broken. I think the lift to get this working is reasonable. The javascript is already there with working triggers. Barring some issues with typeahead, I'll try to fix this in another PR.

@edmullen thanks for the callouts, I'll get on them.

**Comment by adborden** [comment]
Please merge pending these items:
- [ ] SVG `background-image` not loading in firefox https://github.com/18F/fec-style/issues/381
- [ ] Fix alignment of FEC disclaimer
- [ ] Navigation font should be serif

@edmullen I've moved the other items you brougth up into the [main issue](https://github.com/18F/fec-eregs/issues/88) to be addressed in another PR. Does the above sound OK to you?

**Comment by adborden** [comment]
@noahmanger this is ready for another look https://fec-adborden-eregs.18f.gov/

**Comment by noahmanger** [comment]
LGTM. I see the other issues are captured, so I'll merge.

**Pull request merged**
