### PR TITLE
Pin sass version to 3.4.25

### PR DESCRIPTION
**Pull request by vrajmohan**
Not sure whether a better solution is to pin the Ruby version itself.

### CODE REVIEW

**Comment by vrajmohan** [comment]
Perhaps allow us to float with the latest sass version? I am out of my depth here as to which option is better.

**Comment by cmc333333** [comment]
I'd recommend trying to update the `regulations` dependency instead. As of 7.0.1, we're using libsass, which removes the need for ruby altogether.

**Comment by vrajmohan** [comment]
That sounds like a better plan. In the interim, can we merge this PR so that the builds can run again?

**Comment by vrajmohan** [comment]
Created issue #359.

**Pull request merged**
